version: "3.8"

services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - APP_BASE_URL=${APP_URL}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gita-form.rule=Host(`your-domain.com`)"
      - "traefik.http.routers.gita-form.entrypoints=websecure"
      - "traefik.http.routers.gita-form.tls.certresolver=letsencrypt"