// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bepkixkvoxekafvuyxks.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlcGtpeGt2b3hla2FmdnV5eGtzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2NjQ3MzQsImV4cCI6MjA2MjI0MDczNH0.67es9w2SCE7yUBYGLaEiTc2tUiiPk9-G8M0UeCdaOcw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});